Repository apache/incubator-hugegraph-computer, pull requests merged in 2022-11, with the labels that each got.

#190 chore: add apache .asf.yml config
  .asf.yaml
Labels: apache

#189 chore: update a string of ci configs & gitignore & README
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/question_ask.yml
  .github/outdated/.travis.yml
  .github/outdated/cla.yml
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/publish_images.yml
  .github/workflows/release.yml
  .github/workflows/stale.yml
  .gitignore
  README.md
Labels: enhancement

#196 Refactor computer: abstract computer-api from computer-core
  computer-algorithm/pom.xml
  computer-algorithm/src/main/java/com/baidu/hugegraph/computer/algorithm/centrality/betweenness/BetweennessCentralityParams.java
  computer-algorithm/src/main/java/com/baidu/hugegraph/computer/algorithm/centrality/closeness/ClosenessCentralityParams.java
  computer-algorithm/src/main/java/com/baidu/hugegraph/computer/algorithm/centrality/closeness/ClosenessMessage.java
  computer-algorithm/src/main/java/com/baidu/hugegraph/computer/algorithm/centrality/degree/DegreeCentralityParams.java
  computer-algorithm/src/main/java/com/baidu/hugegraph/computer/algorithm/centrality/pagerank/PageRankParams.java
  computer-algorithm/src/main/java/com/baidu/hugegraph/computer/algorithm/community/kcore/KcoreParams.java
  computer-algorithm/src/main/java/com/baidu/hugegraph/computer/algorithm/community/kcore/KcoreValue.java
  computer-algorithm/src/main/java/com/baidu/hugegraph/computer/algorithm/community/lpa/LpaParams.java
  computer-algorithm/src/main/java/com/baidu/hugegraph/computer/algorithm/community/trianglecount/TriangleCountParams.java
  computer-algorithm/src/main/java/com/baidu/hugegraph/computer/algorithm/community/wcc/WccParams.java
  computer-algorithm/src/main/java/com/baidu/hugegraph/computer/algorithm/path/rings/filter/RingsDetectionWithFilterParams.java
  computer-api/pom.xml
  computer-api/src/main/java/com/baidu/hugegraph/computer/algorithm/AlgorithmParams.java
  computer-api/src/main/java/com/baidu/hugegraph/computer/core/config/ComputerOptions.java
  computer-api/src/main/java/com/baidu/hugegraph/computer/core/config/DefaultConfig.java
  computer-api/src/main/java/com/baidu/hugegraph/computer/core/config/EdgeFrequency.java
  computer-api/src/main/java/com/baidu/hugegraph/computer/core/config/HotConfig.java
  computer-api/src/main/java/com/baidu/hugegraph/computer/core/graph/id/IdFactory.java
  computer-api/src/main/java/com/baidu/hugegraph/computer/core/graph/properties/DefaultProperties.java
  computer-api/src/main/java/com/baidu/hugegraph/computer/core/graph/value/IdSet.java
  computer-api/src/main/java/com/baidu/hugegraph/computer/core/graph/value/MapValue.java
  computer-api/src/main/java/com/baidu/hugegraph/computer/core/output/AbstractComputerOutput.java
  computer-api/src/main/java/com/baidu/hugegraph/computer/core/output/hg/HugeGraphOutput.java
  computer-api/src/main/java/com/baidu/hugegraph/computer/core/output/hg/exceptions/WriteBackException.java
  computer-api/src/main/java/com/baidu/hugegraph/computer/core/output/hg/metrics/LoadMetrics.java
  computer-api/src/main/java/com/baidu/hugegraph/computer/core/output/hg/metrics/LoadReport.java
  computer-api/src/main/java/com/baidu/hugegraph/computer/core/output/hg/metrics/LoadSummary.java
  computer-api/src/main/java/com/baidu/hugegraph/computer/core/output/hg/metrics/Printer.java
  computer-api/src/main/java/com/baidu/hugegraph/computer/core/output/hg/task/BatchInsertTask.java
  computer-api/src/main/java/com/baidu/hugegraph/computer/core/output/hg/task/InsertTask.java
  computer-api/src/main/java/com/baidu/hugegraph/computer/core/output/hg/task/SingleInsertTask.java
  computer-api/src/main/java/com/baidu/hugegraph/computer/core/output/hg/task/TaskManager.java
  computer-core/pom.xml
  computer-core/src/main/java/com/baidu/hugegraph/computer/core/graph/id/IdFactory.java
  computer-core/src/main/java/com/baidu/hugegraph/computer/core/network/TransportConf.java
  computer-dist/pom.xml
  computer-dist/src/assembly/travis/build-images.sh
  computer-driver/pom.xml
  computer-driver/src/main/java/com/baidu/hugegraph/computer/driver/config/ComputerOptions.java
  computer-k8s-operator/pom.xml
  computer-k8s-operator/src/main/java/com/baidu/hugegraph/computer/k8s/operator/controller/ComputerJobDeployer.java
  computer-k8s/pom.xml
  computer-k8s/src/main/java/com/baidu/hugegraph/computer/k8s/config/KubeDriverOptions.java
  computer-k8s/src/main/java/com/baidu/hugegraph/computer/k8s/driver/KubernetesDriver.java
  computer-test/src/main/java/com/baidu/hugegraph/computer/driver/ComputerOptionsTest.java
  computer-test/src/main/java/com/baidu/hugegraph/computer/driver/DriverTest.java
  computer-test/src/main/java/com/baidu/hugegraph/computer/driver/DriverTestSuite.java
  computer-test/src/main/java/com/baidu/hugegraph/computer/k8s/AbstractK8sTest.java
  computer-test/src/main/java/com/baidu/hugegraph/computer/k8s/KubernetesDriverTest.java
  computer-test/src/main/java/com/baidu/hugegraph/computer/k8s/MiniKubeTest.java
  computer-test/src/main/java/com/baidu/hugegraph/computer/suite/unit/UnitTestBase.java
  pom.xml
Labels: refactor

#200 [improve][build] Improve package & cli & build image
  .github/workflows/publish_images.yml
  computer-algorithm/Dockerfile
  computer-algorithm/pom.xml
  computer-core/pom.xml
  computer-core/src/main/java/com/baidu/hugegraph/computer/core/util/ComputerContextUtil.java
  computer-core/src/main/java/com/baidu/hugegraph/computer/core/util/ShutdownHook.java
  computer-core/src/main/java/com/baidu/hugegraph/computer/core/worker/WorkerService.java
  computer-dist/Dockerfile
  computer-dist/pom.xml
  computer-dist/src/assembly/static/bin/start-computer.sh
  computer-dist/src/assembly/static/conf/computer.properties
  computer-dist/src/assembly/static/conf/log4j2.xml
  computer-dist/src/assembly/travis/build-images.sh
  computer-dist/src/main/java/com/baidu/hugegraph/computer/dist/HugeGraphComputer.java
  computer-dist/src/main/resources/computer.properties
  computer-k8s-operator/Dockerfile
  computer-k8s-operator/src/main/java/com/baidu/hugegraph/computer/k8s/operator/controller/ComputerJobDeployer.java
  computer-k8s/src/main/java/com/baidu/hugegraph/computer/k8s/Constants.java
  computer-k8s/src/main/java/com/baidu/hugegraph/computer/k8s/config/KubeDriverOptions.java
  computer-k8s/src/main/resources/docker_push.sh
  computer-test/conf/images/docker_push_test.sh
  computer-test/src/main/java/com/baidu/hugegraph/computer/dist/HugeGraphComputerTest.java
  computer-test/src/main/resources/computer-worker1.properties
  computer-test/src/main/resources/computer.properties
  computer-test/src/main/resources/log4j2.xml
  pom.xml
Labels: improvement, build, cli

#201 Improve TriangleCount and ClusteringCoefficient
  computer-algorithm/src/main/java/com/baidu/hugegraph/computer/algorithm/community/cc/ClusteringCoefficient.java
  computer-algorithm/src/main/java/com/baidu/hugegraph/computer/algorithm/community/cc/ClusteringCoefficientOutput.java
  computer-algorithm/src/main/java/com/baidu/hugegraph/computer/algorithm/community/cc/ClusteringCoefficientValue.java
  computer-algorithm/src/main/java/com/baidu/hugegraph/computer/algorithm/community/trianglecount/TriangleCount.java
  computer-algorithm/src/main/java/com/baidu/hugegraph/computer/algorithm/community/trianglecount/TriangleCountValue.java
  computer-api/src/main/java/com/baidu/hugegraph/computer/core/graph/value/IdSet.java
  computer-api/src/main/java/com/baidu/hugegraph/computer/core/graph/value/ListValue.java
  computer-test/src/main/java/com/baidu/hugegraph/computer/algorithm/AlgorithmTestSuite.java
  computer-test/src/main/java/com/baidu/hugegraph/computer/algorithm/community/cc/ClusteringCoefficientTest.java
  computer-test/src/main/java/com/baidu/hugegraph/computer/algorithm/community/trianglecount/TriangleCountTest.java
Labels: algorithm
