Repository apache/incubator-hugegraph-computer, pull requests merged in 2022-12, with the labels that each got.

#214 update antrun plugin
  .gitignore
  computer-dist/pom.xml
Labels: build

#217 chore: enable github rebase option
  .asf.yaml
  computer-dist/src/assembly/travis/load-data-into-hugegraph.sh
Labels: apache

#219 chore: add other license file for provided jar
  computer-dist/release-docs/LICENSE
  computer-dist/release-docs/NOTICE
  computer-dist/release-docs/licenses/LICENSE-apiguardian-api.txt
  computer-dist/release-docs/licenses/LICENSE-automaton.txt
  computer-dist/release-docs/licenses/LICENSE-builder-annotations.txt
  computer-dist/release-docs/licenses/LICENSE-byte-buddy.txt
  computer-dist/release-docs/licenses/LICENSE-commons-text.txt
  computer-dist/release-docs/licenses/LICENSE-computer-algorithm.txt
  computer-dist/release-docs/licenses/LICENSE-computer-driver.txt
  computer-dist/release-docs/licenses/LICENSE-computer-k8s-operator.txt
  computer-dist/release-docs/licenses/LICENSE-computer-k8s.txt
  computer-dist/release-docs/licenses/LICENSE-computer-yarn.txt
  computer-dist/release-docs/licenses/LICENSE-generex.txt
  computer-dist/release-docs/licenses/LICENSE-jakarta.activation.txt
  computer-dist/release-docs/licenses/LICENSE-jaxb-core.txt
  computer-dist/release-docs/licenses/LICENSE-kubernetes-client.txt
  computer-dist/release-docs/licenses/LICENSE-kubernetes-model-admissionregistration.txt
  computer-dist/release-docs/licenses/LICENSE-kubernetes-model-apiextensions.txt
  computer-dist/release-docs/licenses/LICENSE-kubernetes-model-apps.txt
  computer-dist/release-docs/licenses/LICENSE-kubernetes-model-autoscaling.txt
  computer-dist/release-docs/licenses/LICENSE-kubernetes-model-batch.txt
  computer-dist/release-docs/licenses/LICENSE-kubernetes-model-certificates.txt
  computer-dist/release-docs/licenses/LICENSE-kubernetes-model-common.txt
  computer-dist/release-docs/licenses/LICENSE-kubernetes-model-coordination.txt
  computer-dist/release-docs/licenses/LICENSE-kubernetes-model-core.txt
  computer-dist/release-docs/licenses/LICENSE-kubernetes-model-discovery.txt
  computer-dist/release-docs/licenses/LICENSE-kubernetes-model-events.txt
  computer-dist/release-docs/licenses/LICENSE-kubernetes-model-extensions.txt
  computer-dist/release-docs/licenses/LICENSE-kubernetes-model-flowcontrol.txt
  computer-dist/release-docs/licenses/LICENSE-kubernetes-model-metrics.txt
  computer-dist/release-docs/licenses/LICENSE-kubernetes-model-networking.txt
  computer-dist/release-docs/licenses/LICENSE-kubernetes-model-node.txt
  computer-dist/release-docs/licenses/LICENSE-kubernetes-model-policy.txt
  computer-dist/release-docs/licenses/LICENSE-kubernetes-model-rbac.txt
  computer-dist/release-docs/licenses/LICENSE-kubernetes-model-scheduling.txt
  computer-dist/release-docs/licenses/LICENSE-kubernetes-model-storageclass.txt
  computer-dist/release-docs/licenses/LICENSE-kubernetes-server-mock.txt
  computer-dist/release-docs/licenses/LICENSE-logging-interceptor.txt
  computer-dist/release-docs/licenses/LICENSE-mockito-core.txt
  computer-dist/release-docs/licenses/LICENSE-mockwebserver-0.1.8.txt
  computer-dist/release-docs/licenses/LICENSE-mockwebserver-3.12.6.txt
  computer-dist/release-docs/licenses/LICENSE-mvel2.txt
  computer-dist/release-docs/licenses/LICENSE-objenesis.txt
  computer-dist/release-docs/licenses/LICENSE-resourcecify-annotations.txt
  computer-dist/release-docs/licenses/LICENSE-sundr-core.txt
  computer-dist/release-docs/licenses/LICENSE-zjsonpatch.txt
Labels: apache

#218 chore: add apache-release.sh & prepare release
  .gitattributes
  .gitignore
  computer-dist/pom.xml
  computer-dist/scripts/apache-release.sh
  computer-k8s/pom.xml
  pom.xml
Labels: apache, improvement
