Repository apache/incubator-hugegraph-computer, pull requests merged in 2024-03, with the labels that each got.

#304 fix: base-ref/head-ref missed in dependency-review on schedule push
  .github/workflows/codeql-analysis.yml
Labels: bug, size:XS, lgtm

#285 feat(algorithm): support single source shortest path algorithm
  computer-algorithm/src/main/java/org/apache/hugegraph/computer/algorithm/path/shortest/QuantityType.java
  computer-algorithm/src/main/java/org/apache/hugegraph/computer/algorithm/path/shortest/SingleSourceShortestPath.java
  computer-algorithm/src/main/java/org/apache/hugegraph/computer/algorithm/path/shortest/SingleSourceShortestPathCombiner.java
  computer-algorithm/src/main/java/org/apache/hugegraph/computer/algorithm/path/shortest/SingleSourceShortestPathMaster.java
  computer-algorithm/src/main/java/org/apache/hugegraph/computer/algorithm/path/shortest/SingleSourceShortestPathOutput.java
  computer-algorithm/src/main/java/org/apache/hugegraph/computer/algorithm/path/shortest/SingleSourceShortestPathParams.java
  computer-algorithm/src/main/java/org/apache/hugegraph/computer/algorithm/path/shortest/SingleSourceShortestPathValue.java
  computer-api/src/main/java/org/apache/hugegraph/computer/core/combiner/IdListMergeCombiner.java
  computer-api/src/main/java/org/apache/hugegraph/computer/core/combiner/IdSetMergeCombiner.java
  computer-api/src/main/java/org/apache/hugegraph/computer/core/graph/id/IdFactory.java
  computer-api/src/main/java/org/apache/hugegraph/computer/core/graph/value/IdSet.java
  computer-api/src/main/java/org/apache/hugegraph/computer/core/graph/value/ListValue.java
  computer-api/src/main/java/org/apache/hugegraph/computer/core/util/IdUtil.java
  computer-api/src/main/java/org/apache/hugegraph/computer/core/util/JsonUtilExt.java
  computer-test/src/main/java/org/apache/hugegraph/computer/algorithm/AlgorithmTestSuite.java
  computer-test/src/main/java/org/apache/hugegraph/computer/algorithm/path/shortest/SingleSourceShortestPathTest.java
  computer-test/src/main/java/org/apache/hugegraph/computer/core/graph/id/IdFactoryTest.java
  computer-test/src/main/java/org/apache/hugegraph/computer/core/graph/value/ListValueTest.java
  computer-test/src/main/java/org/apache/hugegraph/computer/core/util/IdUtilTest.java
Labels: size:XXL, lgtm

#305 chore: upgrade version to 1.3.0
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/license-checker.yml
  computer-dist/scripts/dependency/known-dependencies.txt
  pom.xml
Labels: documentation, size:M, lgtm
